### ISSUE TITLE
General compost research: material categories

### ISSUE THREAD

**Issue by hmc-cs-mthomas** [Devang101/CompostCalculator#7]

**Comment by echrisinger** [comment]
Here are some resources
https://www.planetnatural.com/composting-101/making/c-n-ratio/
https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=nrcs142p2_052823&ext=pdf
http://norganics.com/index-2/technical-articles/carbon-nitrogen-ratio/
